//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningMS.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseCompletion
    {
        public int CourseCompletionId { get; set; }
        public string UserId { get; set; }
        public int CourseId { get; set; }
        public System.DateTime DateCompleted { get; set; }
    
        public virtual Course Cours { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
